name: 'Changeset release notes'
description: 'Returns release notes for latest changeset release'
outputs:
  release-notes:
    description: 'Release notes'
    value: ${{ steps.run.outputs.release-notes }}

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-workspace
      working-directory: ${{ github.action_path }}

    - name: Get release notes
      id: run
      shell: bash
      run: node ${{ github.action_path }}/main.ts
