name: 'Update Schema'
description: 'Run schema updates using Node.js'
inputs:
  schemaPath:
    description: 'Path to the schema file'
    required: true
  examplesPath:
    description: 'Path to the examples directory'
    required: true
  generateCommand:
    description: 'Command to generate schemas'
    required: true
  tag:
    description: 'Tag for the operation'
    required: true
  githubToken:
    description: 'GitHub Token for authentication'
    required: true
  openApiRepository:
    description: 'OpenAPI repository in format of owner/repo'
    default: 'fingerprintjs/fingerprint-pro-server-api-openapi'
  preRelease:
    description: 'Enable pre-release mode'
    default: "false"
  allowedScopes:
    description: "List of change scopes to allow, comma separated. If left empty, all scopes are allowed."
    default: ""
runs:
  using: 'node20'
  main: 'dist/index.js'
