export const SCHEMA_FILE = 'fingerprint-server-api-schema-for-sdks.yaml'
export const RELEASE_NOTES = 'changesets.zip'
export const EXAMPLES_FILE = 'examples.zip'
export const EXAMPLE_PATH_TO_REPLACE = 'examples/'
export const CHANGESETS_PATH = '.changeset'
