name: 'Analyze Commits'
on:
  workflow_call:
    inputs:
      isTest:
        description: 'Determines whether it is a test run. It is only meant to be used in the DX repo itself.'
        required: false
        type: boolean
        default: false
      nodeVersion:
        description: 'Node version to use'
        required: false
        type: string
        default: 'lts/*'
      installSharedCommitLintConfig:
        description: 'Whether to install the shared commitlint config'
        type: boolean
        default: true
        required: false

jobs:
  commitlint:
    name: Analyze Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Determine package manager'
        run: |
          if [[ -f "pnpm-lock.yaml" ]]; then
            echo "Using pnpm"
            echo "PACKAGE_MANAGER=pnpm" >> $GITHUB_ENV
            echo "PACKAGE_MANAGER_CACHE=" >> $GITHUB_ENV
          elif [[ -f "yarn.lock" ]]; then
            echo "Using yarn"
            echo "PACKAGE_MANAGER=yarn" >> $GITHUB_ENV
            echo "PACKAGE_MANAGER_CACHE=yarn" >> $GITHUB_ENV
          else
            echo "No package manager lock file found"
            echo "PACKAGE_MANAGER=npm" >> $GITHUB_ENV
            echo "PACKAGE_MANAGER_CACHE=" >> $GITHUB_ENV
          fi
      - if: ${{ env.PACKAGE_MANAGER == 'pnpm' }}
        name: 'Install pnpm'
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 8
      - name: 'Install latest node version'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: ${{ env.PACKAGE_MANAGER_CACHE }}
      - name: Init package for non-JS project
        if: ${{ hashFiles('package.json') == '' }}
        run: npm init -y
      - name: 'Install Node packages'
        run: $PACKAGE_MANAGER install
      - name: 'Install commit lint config'
        if: ${{ inputs.installSharedCommitLintConfig }}
        run: $PACKAGE_MANAGER install @fingerprintjs/commit-lint-dx-team@latest
      - uses: wagoid/commitlint-github-action@5ce82f5d814d4010519d15f0552aec4f17a1e1fe
        id: commitlint
      - if: ${{ failure() && steps.commitlint.outcome == 'failure' }}
        name: 'Format commitlint results'
        id: commitlint_formatted_results
        run: |
          results='${{ steps.commitlint.outputs.results }}'
          formatted=$(echo "$results" | jq -r '.[] | select(.valid == false) | "**Commit:** \(.hash) `\(.message)`\n**Errors:**\n\(.errors | map("- " + .) | join("\n"))\n\n---"')
          echo "formatted<<EOF" >> $GITHUB_OUTPUT
          echo "$formatted" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash
      - if: ${{ failure() && steps.commitlint.outcome == 'failure' }}
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        with:
          header: Commitlint
          recreate: true
          message: |
            ## Wrong commit message format detected
            We use [Semantic Commit Messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) in our project.

            > **Warning**
            > Probably you forgot to activate local git hooks.

            Run the next command in the project root to activate local hooks:
            ```sh
            sh ./install_hooks.sh
            ```

            More info you can find in [job logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ### Commitlint Errors
            ${{ steps.commitlint_formatted_results.outputs.formatted }}
      - if: ${{ success() }}
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        with:
          header: Commitlint
          hide: true
          hide_classify: 'OUTDATED'
  release-notes-comment:
    name: Generate release notes preview
    runs-on: ubuntu-latest
    env:
      TEST_MESSAGE: ${{ inputs.isTest && '### ⚠️ This is a test run of the release-notes-comment action that can be found in .github/workflows/analyze-commits.yml' || ''}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Install latest node version'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
      - name: Collect semantic-release-info
        id: semantic_release_info
        uses: fingerprintjs/action-semantic-release-info@v2
      - if: ${{ steps.semantic_release_info.outputs.no_release == 'false' }}
        name: Add comment to the PR
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        with:
          header: ReleasePreview
          recreate: true
          message: |
            ## This PR will create a ${{steps.semantic_release_info.outputs.type}} release :rocket:
            ${{ env.TEST_MESSAGE }}           
            ${{steps.semantic_release_info.outputs.notes}}
      - if: ${{ steps.semantic_release_info.outputs.no_release == 'true' }}
        name: Add comment to the PR
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        with:
          header: ReleasePreview
          recreate: true
          message: |
            ## This PR will not create a new release :rocket:
            ${{ env.TEST_MESSAGE }}
      - name: Add release notes preview to the job summary
        if: ${{ steps.semantic_release_info.outputs.no_release == 'false' }}
        run: |
          echo "## This PR will create a ${{steps.semantic_release_info.outputs.type}} release :rocket:" >> $GITHUB_STEP_SUMMARY
          echo ${{ env.TEST_MESSAGE }} >> $GITHUB_STEP_SUMMARY
          echo "${{steps.semantic_release_info.outputs.notes}}" >> $GITHUB_STEP_SUMMARY
      - name: Add release notes preview to the job summary
        if: ${{ steps.semantic_release_info.outputs.no_release == 'true' }}
        run: |
          echo "## This PR will not create a new release :rocket:" >> $GITHUB_STEP_SUMMARY
          echo ${{ env.TEST_MESSAGE }} >> $GITHUB_STEP_SUMMARY
