name: Check template consistency
description: Check template consistency

on:
  workflow_call:
    inputs:
      generate-command:
        description: 'Command for generating code from OpenAPI schema'
        required: true
        type: string

jobs:
  check-template-consistency:
    name: Check template consistency
    runs-on: ubuntu-latest
    outputs:
      has_diff: ${{ steps.diff.outputs.has_diff }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate code
        run: |
          ${{ inputs.generate-command }}

      - name: Get diff
        id: diff
        run: |
          local_diff=$(git diff --name-only HEAD)
          
          if [[ -z "$local_diff" ]]; then
            echo "has_diff=0" >> "$GITHUB_OUTPUT"
          else
            echo "diff<<EOF" >> "$GITHUB_OUTPUT"
            echo "$local_diff" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
            echo "has_diff=1" >> "$GITHUB_OUTPUT"
          fi

      - name: Print diff details
        run: |
          echo "${{ steps.diff.outputs.diff }}"
          echo "${{ steps.diff.outputs.has_diff }}"

      - name: Add comment
        if: steps.diff.outputs.has_diff == '1'
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        with:
          header: 'template-consistency'
          message: |
            ⚠️ Looks like you've edited generated files, instead of related template files.
            
            Following files have been changed:
            `${{ steps.diff.outputs.diff }}`
            
            To fix this warning, modify the template files instead and run the following command:
            ```bash
            ${{ inputs.generate-command }}
            ```

      - name: Remove comment
        if: steps.diff.outputs.has_diff != '1'
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31
        with:
          header: 'template-consistency'
          delete: true

  # We need to fail in a separate job, otherwise the comment from the previous job will be removed
  fail-on-diff:
    name: Fail on diff
    runs-on: ubuntu-latest
    needs: check-template-consistency
    steps:
      - name: Fail the job
        if: ${{ needs.check-template-consistency.outputs.has_diff == '1' }}
        run: exit 1