name: 'Run tests & check coverage workflow'
on:
  workflow_call:
    inputs:
      nodeVersion:
        description: 'Node version to use'
        required: false
        type: string
        default: 'lts/*'
      testScript:
        type: string
        required: false
        description: The test script to run.
        default: npx jest
      runAfterInstall:
        type: string
        required: false
        description: Commands to run after installing dependencies.

jobs:
  run-tests-check-coverage:
    runs-on: ubuntu-20.04
    name: Run tests & check coverage
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: 'Determine package manager'
        run: |
          if [[ -f "pnpm-lock.yaml" ]]; then
            echo "Using pnpm"
            echo "PACKAGE_MANAGER=pnpm" >> $GITHUB_ENV
          else
            echo "Using yarn"
            echo "PACKAGE_MANAGER=yarn" >> $GITHUB_ENV
          fi

      - if: ${{ env.PACKAGE_MANAGER == 'pnpm' }}
        name: 'Install pnpm'
        uses: pnpm/action-setup@ebcfd6995dade4b0104ac774445cef8b3b4635b0
        with:
          version: 8

      - name: 'Install latest node version'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: ${{ env.PACKAGE_MANAGER }}

      - name: Install Node packages
        run: $PACKAGE_MANAGER install

      - name: 'Run after install commands'
        run: ${{ inputs.runAfterInstall }}
        if: ${{ inputs.runAfterInstall != '' }}

      - name: Build
        run: $PACKAGE_MANAGER build

      - name: Run tests and prepare coverage report
        run: $PACKAGE_MANAGER test:coverage

      - name: Read coverage text report
        uses: fingerprintjs/action-coverage-report-md@v1
        id: coverage-md

      - name: Jest coverage comment
        id: coverage
        uses: ArtiomTr/jest-coverage-report-action@df2b025553c31d68f84be6337843e277e2576844
        with:
          package-manager: ${{ env.PACKAGE_MANAGER }}
          output: report-markdown
          test-script: ${{ inputs.testScript }}

      - name: Add comment with coverage report
        uses: marocchino/sticky-pull-request-comment@adca94abcaf73c10466a71cc83ae561fd66d1a56
        with:
          message: |
            ${{ steps.coverage.outputs.report }}
            <details>
              <summary>Show full coverage report</summary>

              ${{ steps.coverage-md.outputs.markdownReport }}
            </details>

      - name: Add coverage report to the job summary
        run: |
          {
            echo "## Code Coverage" 
            echo "" 
            echo "${{ steps.coverage-md.outputs.markdownReport }}"
          } >> $GITHUB_STEP_SUMMARY
