name: Create PR to Main on release

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      prerelease:
        required: true
        type: boolean
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  create-pr-to-main-on-release:
    runs-on: ubuntu-latest
    steps:
      - name: Abort if it's not a pre-release
        if: inputs.prerelease == false
        run: exit 1
      - name: Checkout test branch
        uses: actions/checkout@v3
        with:
          ref: 'test'

      - name: Create Pull Request from tag branch to main
        run: |
          gh pr create --title "Release ${{ inputs.tag_name }}" --body "Release ${{ inputs.tag_name }}" --base main --head test --repo ${{ inputs.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
