name: 'Preview changeset release'
on:
  workflow_call:
    inputs:
      pr-title:
        description: Title of created PR
        required: true
        type: string
      node-version:
        description: 'Node version to use'
        required: false
        type: string
        default: 'lts/*'
      changeset-command:
        description: 'Command used to generate changeset. It will be used in a suggestion if there are no changesets.'
        required: false
        type: string
        default: 'pnpm exec changeset'
      prepare-command:
        description: 'Command to run for project preparation (e.g., installing dependencies).'
        required: false
        type: string

jobs:
  preview:
    name: Generate release notes
    runs-on: ubuntu-latest
    if: ${{ !contains('[changeset] ', inputs.pr-title) }}
    steps:
      - uses: actions/checkout@v7

      - name: 'Determine package manager'
        run: |
          if [[ -f "yarn.lock" ]]; then
            echo "Using yarn"
            echo "PACKAGE_MANAGER=yarn" >> $GITHUB_ENV
          else
            echo "Using pnpm"
            echo "PACKAGE_MANAGER=pnpm" >> $GITHUB_ENV
          fi

      - if: ${{ env.PACKAGE_MANAGER == 'pnpm' }}
        name: 'Install pnpm'
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: 'Install latest node version'
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ env.PACKAGE_MANAGER }}

      - name: Install dependencies
        run: $PACKAGE_MANAGER install

      - name: Prepare project
        if: ${{ inputs.prepare-command }}
        run: ${{ inputs.prepare-command }}

      - name: 'Checkout dx-team-toolkit actions'
        uses: actions/checkout@v7
        with:
          repository: fingerprintjs/dx-team-toolkit
          ref: ${{ github.workflow_sha }}
          path: _dx-toolkit
          sparse-checkout: .github/actions
          sparse-checkout-cone-mode: false

      - name: 'Get release notes'
        id: notes
        uses: ./_dx-toolkit/.github/actions/changeset-release-notes
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 'Add comment to PR'
        if: steps.notes.outputs.release-notes != ''
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: Release notes
          recreate: true
          message: |
            ### 🚀 Following releases will be created using changesets from this PR:
            
            ${{ steps.notes.outputs.release-notes }}

      - name: 'Add comment to PR'
        if: steps.notes.outputs.release-notes == ''
        uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0 # v3.0.4
        with:
          header: Release notes
          recreate: true
          message: |
            ⚠️ This PR doesn't contain any changesets. If there are user-facing changes, don't forget to run:
            ```bash
            ${{ inputs.changeset-command }}
            ```
            to create a changeset.

      - name: 'Add release notes preview to the job summary'
        if: steps.notes.outputs.release-notes != ''
        run: |
          echo "${{ steps.notes.outputs.release-notes }}" >> $GITHUB_STEP_SUMMARY

