name: 'Release SDK using changesets'
on:
  workflow_call:
    inputs:
      prepare-command:
        description: 'Command to run for project preparation (e.g., installing dependencies).'
        required: false
        type: string
      version-command:
        description: 'Command to run for project versioning'
        default: pnpm exec changeset version
        type: string
      publish-command:
        description: 'Command to run for project publishing'
        default: pnpm exec changeset publish
        type: string
      language:
        description: 'Programming language for the project. Supported values are "java", "dotnet", "python", "golang", "flutter" and "php".'
        required: true
        type: string
      language-version:
        description: 'Version of the programming language to setup.'
        required: true
        type: string
      java-version:
        description: 'Version of Java to setup.'
        required: false
        type: string
        default: '11'
    secrets:
      GH_RELEASE_TOKEN:
        description: 'GitHub token with permissions to create releases and perform other necessary operations.'
        required: false
      NPM_AUTH_TOKEN:
        description: 'NPM authentication token for publishing packages.'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup language
        uses: fingerprintjs/dx-team-toolkit/.github/actions/setup-lang@v1
        with:
          language: ${{ inputs.language }}
          language-version: ${{ inputs.language-version }}
          java-version: ${{ inputs.java-version }}

      - name: 'Prepare project'
        if: ${{ inputs.prepare-command != '' }}
        run: ${{ inputs.prepare-command }}

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 9
          run_install: 'true'

      - name: 'Install changeset'
        run: 'pnpm install @changesets/cli --global'

      - name: Create Release
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9
        with:
          publish: ${{ inputs.publish-command }}
          version: ${{ inputs.version-command }}
          commit: 'chore(release): changeset created a new release'
          title: 'Release [changeset]'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
