name: 'Release SDK using changesets'
on:
  workflow_call:
    inputs:
      prepare-command:
        description: 'Command to run for project preparation (e.g., installing dependencies).'
        required: false
        type: string
    secrets:
      GH_RELEASE_TOKEN:
        description: 'GitHub token with permissions to create releases and perform other necessary operations.'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 'Prepare project'
        if: ${{ inputs.prepare-command != '' }}
        run: ${{ inputs.prepare-command }}

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 9
          run_install: 'true'

      - name: 'Output ref'
        run: echo ${{ github.ref }}

      - name: 'Enter pre-release mode on test branch'
        if: github.ref == 'refs/heads/test' && hashFiles('.changeset/pre.json') == ''
        run: pnpm exec changeset pre enter test

      - name: Create Release
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9
        with:
          publish: pnpm exec changeset publish
          version: pnpm exec changeset version
          commit: 'chore(release): changeset created a new release'
          title: 'Release [changeset]'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
