name: 'Release SDK using changesets'
on:
  workflow_call:
    inputs:
      prepare-command:
        description: 'Command to run for project preparation (e.g., installing dependencies).'
        required: false
        type: string
      version-command:
        description: 'Command to run for project versioning'
        default: pnpm exec changeset version
        type: string
      publish-command:
        description: 'Command to run for project publishing'
        default: pnpm exec changeset publish
        type: string
      language:
        description: 'Programming language for the project. Supported values are "java", "dotnet", "python", "golang", "flutter" and "php".'
        required: true
        type: string
      language-version:
        description: 'Version of the programming language to setup.'
        required: true
        type: string
      java-version:
        description: 'Version of Java to setup.'
        required: false
        type: string
        default: '11'
      appId:
        type: string
        required: true
        description: 'GitHub app id for release process.'
      runnerAppId:
        type: string
        default: ''
        required: false
        description: 'GitHub app id for creating PR.'
    secrets:
      APP_PRIVATE_KEY:
        description: 'GitHub App private key to request GitHub token for release process.'
        required: true
      RUNNER_APP_PRIVATE_KEY:
        description: 'GitHub App private key to request GitHub token for creating PR.'
        required: false
      NPM_AUTH_TOKEN:
        description: 'NPM authentication token for publishing packages.'
        required: false

jobs:
  determine-changesets-step:
    runs-on: ubuntu-latest
    outputs:
      action: ${{ steps.changeset-determine-step.outputs.action }}
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Setup pnpm'
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 9
          run_install: 'true'

      - name: 'Install changesets'
        run: 'pnpm install @changesets/cli --global'

      - name: Determine changesets step
        id: changeset-determine-step
        uses: fingerprintjs/dx-team-toolkit/.github/actions/changeset-determine-step@4b8be0c79af46ddb5b4812025fccb6177e1979ce
  create-pr:
    runs-on: ubuntu-latest
    needs: determine-changesets-step
    if: needs.determine-changesets-step.outputs.action == 'pr' || inputs.runnerAppId != ''
    steps:
      - name: 'Get token for the GitHub App'
        if: ${{ inputs.appId != '' }}
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup language
        uses: fingerprintjs/dx-team-toolkit/.github/actions/setup-lang@v1
        with:
          language: ${{ inputs.language }}
          language-version: ${{ inputs.language-version }}
          java-version: ${{ inputs.java-version }}

      - name: 'Prepare project'
        if: ${{ inputs.prepare-command != '' }}
        run: ${{ inputs.prepare-command }}

      # Setup PNPM for other projects than node to install changeset globally
      - name: 'Setup pnpm'
        if: ${{ inputs.language != 'node' }}
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 9
          run_install: 'true'

      - name: 'Install changesets'
        run: 'pnpm install @changesets/cli --global'

      - name: Create Release PR
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9
        with:
          version: ${{ inputs.version-command }}
          commit: 'chore(release): changeset created a new release'
          title: 'Release [changeset]'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
  release:
    runs-on: ubuntu-latest
    environment: production
    needs: determine-changesets-step
    if: needs.determine-changesets-step.outputs.action == 'publish' || inputs.runnerAppId == ''
    steps:
      - name: 'Get token for the GitHub App'
        if: ${{ inputs.appId != '' }}
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup language
        uses: fingerprintjs/dx-team-toolkit/.github/actions/setup-lang@v1
        with:
          language: ${{ inputs.language }}
          language-version: ${{ inputs.language-version }}
          java-version: ${{ inputs.java-version }}

      - name: 'Prepare project'
        if: ${{ inputs.prepare-command != '' }}
        run: ${{ inputs.prepare-command }}

      # Setup PNPM for other projects than node to install changeset globally
      - name: 'Setup pnpm'
        if: ${{ inputs.language != 'node' }}
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 9
          run_install: 'true'

      - name: 'Install changesets'
        run: 'pnpm install @changesets/cli --global'

      - name: Create Release
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9
        with:
          publish: ${{ inputs.publish-command }}
          version: ${{ inputs.version-command }}
          commit: 'chore(release): changeset created a new release'
          title: 'Release [changeset]'
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
