name: Create Prerelease Branch and Force Push

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
        description: 'Branch to reset'
      appId:
        type: string
        required: true
        description: 'GitHub app id for release process'
    secrets:
      APP_PRIVATE_KEY:
        description: 'GitHub App token to request GitHub token'
        required: true

jobs:
  create-branch-and-force-push:
    name: "Create branch from main and force push"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Get token for the GitHub App'
        if: ${{ inputs.appId != '' }}
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Configure git with App token
        if: steps.app-token.outputs.token != ''
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git config --global http.https://github.com/.extraheader "AUTHORIZATION: bearer \${{ steps.app-token.outputs.token }}"

      - name: Create and switch to branch
        run: |
          git checkout -b ${{ inputs.branch_name }} origin/main

      - name: Force push to branch
        run: git push origin ${{ inputs.branch_name }} --force
