name: 'Run server SDK E2E tests'
on:
  workflow_call:
    inputs:
      sdkVersion:
        description: 'Version of the SDK to test'
        required: false
        default: latest
        type: string
      sdk:
        description: 'Type of SDK to test, can be: go, dotnet, node, php, python, java'
        type: string
        required: true
      appId:
        type: string
        required: true
        description: 'GitHub app id to access the repository with E2E tests'
      commitSha:
        type: string
        required: false
        description: 'SHA of commit that triggered the workflow'
    secrets:
      APP_PRIVATE_KEY:
        description: 'GitHub App token to request GitHub token'
        required: true
      SLACK_WEBHOOK_URL:
        description: 'Slack webhook URL for sending job status'
        required: true

jobs:
  e2e-tests:
    name: 'E2E Tests'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: 'Get token for the GitHub App'
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: fingerprintjs
          repositories: dx-team-orchestra

      - uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0
        with:
          repository: fingerprintjs/dx-team-orchestra
          token: ${{ steps.app-token.outputs.token }}
          event-type: 'e2e_tests'
          client-payload: |-
            {
              "sdk-version": "${{ inputs.sdkVersion }}",
              "run-node-sdk-tests": ${{ inputs.sdk == 'node' }},
              "run-go-sdk-tests": ${{ inputs.sdk == 'go' }},
              "run-dotnet-sdk-tests": ${{ inputs.sdk == 'dotnet' }},
              "run-php-sdk-tests": ${{ inputs.sdk == 'php' }},
              "run-python-sdk-tests": ${{ inputs.sdk == 'python' }},
              "run-java-sdk-tests": ${{ inputs.sdk == 'java' }},
              "repository": ${{ github.repository }},
              "sha": ${{ inputs.commitSha }}
            }

  report_status:
    needs: e2e-tests
    if: always()
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/report-workflow-status.yml@v1
    with:
      notification_title: '${{inputs.sdk}} SDK E2E Tests has {status_message}'
      job_status: ${{ needs.e2e-tests.result }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}