name: Check coverage for PR

on:
  pull_request:

jobs:
  run-tests-check-coverage:
    name: Run tests & check coverage
    permissions:
      checks: write
      pull-requests: write
    uses: ./.github/workflows/coverage-diff.yml
    with:
      runAfterInstall: git config --global user.email "test@example.com" && git config --global user.name "Test User"
