name: Test check template consistency

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  check-template-consistency:
    uses: ./.github/workflows/check-template-consistency.yml
    with:
      generate-command: 'touch test.txt && git add test.txt'
