name: 'Preview changeset release'
on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  preview:
    name: Preview changeset release
    uses: ./.github/workflows/preview-changeset-release.yml
    with:
      pr-title: ${{ github.event.pull_request.title }}



