name: 'Update server-side SDK schema'
on:
  workflow_call:
    inputs:
      language:
        description: 'Programming language for the project. Supported values are "java", "dotnet", "python", "golang", "flutter" and "php".'
        required: true
        type: string
      language-version:
        description: 'Version of the programming language to setup.'
        required: true
        type: string
      java-version:
        description: 'Version of Java to setup.'
        required: false
        type: string
        default: '11'
      prepare-command:
        description: 'Command to run for project preparation (e.g., installing dependencies).'
        required: false
        type: string
      generate-command:
        description: 'Command for generating code from OpenAPI schema'
        required: true
        type: string
      tag:
        description: 'Tag for the OpenAPI release.'
        required: true
        type: string
      schema-path:
        description: 'Path to the OpenAPI schema.'
        required: true
        type: string
      examples-path:
        description: 'Path to the OpenAPI examples.'
        required: true
        type: string
      app-id:
        type: string
        required: true
        description: 'GitHub app id for release process'
      repository:
        type: string
        required: true
        description: 'Name of the repository in format'
      owner:
        type: string
        required: false
        description: 'Owner of the repository'
        default: fingerprintjs
      pre-release:
        type: boolean
        required: false
        description: 'Whether to start a pre-release changeset flow'
        default: false
      ignored-scopes:
        description: "List of change scopes to ignore, comma separated"
        required: false
        type: string
        default: ""

    secrets:
      APP_PRIVATE_KEY:
        description: 'GitHub App token to request GitHub token'
        required: true

jobs:
  update:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: 'Get token for the GitHub App'
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c
        id: app-token
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: '${{ inputs.repository }}'
          owner: '${{ inputs.owner }}'

      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: ${{ inputs.owner }}/${{ inputs.repository }}

      - name: Setup language
        uses: fingerprintjs/dx-team-toolkit/.github/actions/setup-lang@v1
        with:
          language: ${{ inputs.language }}
          language-version: ${{ inputs.language-version }}
          java-version: ${{ inputs.java-version }}
        
      - name: 'Setup pnpm'
        if: ${{ inputs.language == 'node' }}
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 9

      - name: 'Install Node'
        if: ${{ inputs.language == 'node' }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.language-version }}
          cache: 'pnpm'

      - name: Install Dependencies for Node SDK
        if: ${{ inputs.language == 'node' }}
        run: pnpm install
        env:
          CI: true

      - name: Set git config
        run: |
          git config --global --add --bool push.autoSetupRemote true

      - name: Update schema
        uses: fingerprintjs/dx-team-toolkit/.github/actions/update-sdk-schema@v1
        with:
          schemaPath: ${{ inputs.schema-path }}
          examplesPath: ${{ inputs.examples-path }}
          generateCommand: ${{ inputs.generate-command }}
          tag: ${{ inputs.tag }}
          githubToken: '${{ steps.app-token.outputs.token }}'
          preRelease: '${{ inputs.pre-release }}'
          ignoredScopes: ${{ inputs.ignored-scopes }}

      - name: Add & Commit
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
        with:
          add: '.'
          github_token: ${{ steps.app-token.outputs.token }}
          message: 'feat: update OpenAPI schema'
          push: 'false'


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
        with:
          title: 'OpenAPI schema sync'
          token: ${{ steps.app-token.outputs.token }}
          branch: feat/open-api-${{ inputs.tag }}

