name: Setup language
description: 'Setups language'
inputs:
  language:
    description: 'Programming language for the project. Supported values are "java", "dotnet", "python", "golang", "flutter" and "php".'
    required: true
    type: string
  language-version:
    description: 'Version of the programming language to setup.'
    required: true
    type: string
  java-version:
    description: 'Version of Java to setup.'
    required: false
    type: string
    default: '11'
runs:
  using: "composite"
  steps:
    - name: 'Install Java'
      if: ${{ inputs.language != 'flutter' }} # Flutter requires newer version of Java that already installed in worker
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: ${{ inputs.java-version }}
        cache: ${{ inputs.language == 'java' && 'gradle' || '' }}

    - name: 'Install DotNET'
      if: ${{ inputs.language == 'dotnet' }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.language-version }}

    - name: 'Install Python'
      if: ${{ inputs.language == 'python' }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.language-version }}

    - name: 'Install Golang'
      if: ${{ inputs.language == 'golang' }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.language-version }}

    - name: 'Install Flutter'
      if: ${{ inputs.language == 'flutter' }}
      uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
      with:
        flutter-version: ${{ inputs.language-version }}
        channel: 'stable'

    - name: 'Install PHP'
      if: ${{ inputs.language == 'php' }}
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
      with:
        php-version: ${{ inputs.language-version }}
        coverage: none
        tools: composer:v2

    - name: 'Install Terraform'
      if: ${{ inputs.language == 'terraform' }}
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
      with:
        terraform_version: ${{ inputs.language-version }}

    - name: 'Install Node'
      if: ${{ inputs.language == 'node' }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.language-version }}

    - name: 'Setup pnpm'
      if: ${{ inputs.language == 'node' }}
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      with:
        version: 9
        run_install: 'true'

